//
// Aspia Project
// Copyright (C) 2016-2026 Dmitry Chapyshev <dmitry@aspia.ru>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//

syntax = "proto3";

option optimize_for = LITE_RUNTIME;

package proto.storage;

// The encrypted column of a host record.
message HostBlob
{
    string address  = 1;
    string username = 2;
    string password = 3;
}

// The encrypted column of a router record.
message RouterBlob
{
    string address     = 1;
    string username    = 2;
    string password    = 3;
    bytes device_token = 4;
}

// The exported backup. |data| and |verifier| are sealed with a key derived from |salt| and the
// password of the backup. |verifier| tells a wrong password from a damaged file.
message BackupFile
{
    message Router
    {
        string guid         = 1;
        string display_name = 2;
        string address      = 3;
        uint32 session_type = 4;
        string username     = 5;
        string password     = 6;
    }

    message RouterHost
    {
        string router_guid = 1;
        uint64 host_id     = 2;
        string username    = 3;
        string password    = 4;
    }

    message LocalGroup
    {
        string guid        = 1;
        string parent_guid = 2;
        string name        = 3;
        string comment     = 4;
    }

    message LocalHost
    {
        string guid        = 1;
        string group_guid  = 2;
        string router_guid = 3;
        string name        = 4;
        string comment     = 5;
        string address     = 6;
        string username    = 7;
        string password    = 8;
        int64 create_time  = 9;
        int64 modify_time  = 10;
        int64 connect_time = 11;
    }

    message Content
    {
        repeated Router routers          = 1;
        repeated RouterHost router_hosts = 2;
        repeated LocalGroup local_groups = 3;
        repeated LocalHost local_hosts   = 4;
    }

    uint32 version = 1;
    bytes salt     = 2;
    bytes verifier = 3;
    bytes data     = 4;
}
